# Generated by Django 3.2.12 on 2022-05-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_vote_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='vote_users',
        ),
    ]
